version: "2"
services:
  voicevox_engine:
    # CPUの場合は voicevox/voicevox_engine:cpu-ubuntu20.04-latest を使用
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    tty: true