name: Trigger auto deployment for kyumochan

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/kyumochan-AutoDeployTrigger-1b087976-909d-4d5f-ba44-58c7cda220ef.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.KYUMOCHAN_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KYUMOCHAN_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KYUMOCHAN_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.KYUMOCHAN_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KYUMOCHAN_REGISTRY_PASSWORD }}
          containerAppName: kyumochan
          resourceGroup: aaa
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


